### PR TITLE
Small refactoring of interpose/localbypass/clienturl 

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

## Motivation

1. Moved clienturl to tools, that reduced lines of code and entities count. 
2. Added clienturl.Map and reused it in interpose and localbypass chain elements.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Overall good idea.  I'd suggest though that:

1. The context bit go into pkg/tools/clienturlctx
2. The Map bit go into pkg/tools/clienturlmap

This way you wind up with clean pkg naming that doesn't collide with clienturl chain elements.

**Comment by denis-tingajkin** [comment]
@edwarnicke awesome idea, fixed

**Comment by edwarnicke** [comment]
> @edwarnicke awesome idea, fixed

Ah.. I updated my comment to suggest stringurl not clienturlmap as package names there ... makes things a little more generic, in case there's a need for stringurl outside the clienturl context :)

**Comment by denis-tingajkin** [comment]
@edwarnicke Indeed `string url` looks better and potentially can be reused

**Pull request merged**
