### PR TITLE
Add nsmgr-proxy chain elements + interdomain unit tests

### PR DESCRIPTION
**Pull request by denis-tingajkin**
Signed-off-by: Denis Tingajkin <denis.tingajkin@xored.com>

## Motivation
https://github.com/networkservicemesh/sdk/issues/406

1. Added nsmgr-proxy chains
2. Added `sandbox` tool for unit testing NSM chains
3. Covered interdomain case by unit tests

### CODE REVIEW

**Comment by edwarnicke** [comment]
Is it possible to break this into smaller easier to review pieces?  There seem to be quite some several things going on in this PR.

**Comment by denis-tingajkin** [comment]
> Is it possible to break this into smaller easier to review pieces?

@edwarnicke yes, sure, I'll split this PR into 4 pieces

**Comment by denis-tingajkin** [comment]
@edwarnicke Plan to split this PR to next parts:

1. Add registry chains
2. Move `chains/chainstest` to `tools/sandbox` and add possible to use by default registry/chains from part1
3. Add networkservice cache chain element to store selected nse URL for the request
4. Fix found bugs in existing proxy registry chain elements
5. Add proxynsmgr chain elements + unit tests
6. Add proxynsmgr into netowkrservice/chains and cover it via `sandbox` from step 2

**Comment by haiodo** [comment]
@denis-tingajkin converted to Draft to prevent accidental merge :-)

**Comment by denis-tingajkin** [comment]
This PR has been split into separate parts.

**Pull request closed without merging**
