### PR TITLE
optl: Histogram to Counter

### PR DESCRIPTION
**Pull request by LionelJouin**
## Description

For the kind of metrics currently colllected in NSM (rx/tx packets/bytes, drops...), Having counters is more appropriate than using histogram.

Probably I will need to save the previous value and apply the difference since counter only have a "Add" function.

I also updated the open telemetry dependency to v1.16.0. Updating to golang 1.20 is required for this version of OpenTelemetry.

## Issue link

https://github.com/networkservicemesh/sdk/issues/1464

## How Has This Been Tested?
- [ ] Added unit testing to cover
- [x] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes
- [ ] Bug fix
- [ ] New functionality
- [ ] Documentation
- [x] Refactoring
- [ ] CI

### CODE REVIEW

**Review by denis-tingaikin — COMMENTED** [review]
Looks good.

Could we update go in the separate PR?

Also, something is happend with build, could you have a look at job result?

**Comment by glazychev-art** [comment]
I think first we need to update [.github](https://github.com/networkservicemesh/.github) before, since we are using reusable workflow, and there is v1.18.
(here for example - https://github.com/networkservicemesh/.github/blob/main/.github/workflows/build-and-test.yaml#L22)

**Comment by LionelJouin** [comment]
https://github.com/networkservicemesh/.github/pull/32

**Comment by LionelJouin** [comment]
Thank you @denis-tingaikin, how does it work? I can still see this go version error: https://github.com/networkservicemesh/sdk/actions/runs/5343501614/jobs/9759105840?pr=1467

**Comment by denis-tingaikin** [comment]
@LionelJouin My guess that you need simply force push the branch

**Comment by LionelJouin** [comment]
Still got errors, I tried `go test -race ./...` and `go test -coverprofile=coverage-ubuntu-latest.txt -covermode=atomic -race ./...` locally and had no problem.

**Comment by denis-tingaikin** [comment]
Could you add option `-count 1` ?

```bash
go test -race ./... -count 1
```

Seems to me we have issues in the sdk. 
Anyway lets try to quickly fix the problems if its actually is not quick we'll continue on our side ;)

**Comment by LionelJouin** [comment]
Thank you, just tried, and same, all tests passed with no problem.

**Comment by LionelJouin** [comment]
@denis-tingaikin did you changed anything? Now only macos is failing (I don't have macos)

**Comment by denis-tingaikin** [comment]
@LionelJouin I've restarted job a few times and seems like everything is passed. I think we should merge it and stabilize CI in separate PR @glazychev-art thoughts?

**Review by denis-tingaikin — APPROVED** [review]

**Review by glazychev-art — APPROVED** [review]
I agree. Most likely, the instabilities are not related to this PR.

**Pull request merged**
