### PR TITLE
fix: authorize client should check tokens on backward

### PR DESCRIPTION
**Pull request by denis-tingaikin**
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>

## Issue
authorize client should check tokens on backward because on forward it have not server's cert and also it will cover much more cases.

### CODE REVIEW

**Comment by edwarnicke** [comment]
Should we also then put the authorize *last* in the client chain?  And if we reject, we should *definitely* make sure to Close down the chain.

**Comment by denis-tingaikin** [comment]
> And if we reject, we should definitely make sure to Close down the chain.

Sure it is already done, have a look at:  pkg/networkservice/common/authorize/client.go:62

 > Should we also then put the authorize last in the client chain? 
 
 I'm not sure about this because in general, we need to verify tokens that returned from the remote side. 
 Do you see any scenario where it is required?

**Comment by edwarnicke** [comment]
> > Should we also then put the authorize last in the client chain?
> 
> I'm not sure about this because in general, we need to verify tokens that returned from the remote side.
> Do you see any scenario where it is required?

That's actually my point.  Since we are checking policy on *return*, we want to accept/reject *before* doing any other work in the client on return.  So we want to do:

```golang
chain.NewNetworkServiceClient(
		append(
			append([]networkservice.NetworkServiceClient{
				updatepath.NewClient(opts.name),
				serialize.NewClient(),
				heal.NewClient(ctx, networkservice.NewMonitorConnectionClient(cc), opts.onHeal),
				refresh.NewClient(ctx),
				metadata.NewClient(),
			}, opts.additionalFunctionality...),
                          opts.authorizeClient,
			networkservice.NewNetworkServiceClient(cc),
		)...)
```

rather than:
https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/chains/client/client.go#L92-L103

So that we check the authorization as early as possible in the return part of the chain.

**Comment by edwarnicke** [comment]
> > And if we reject, we should definitely make sure to Close down the chain.
> 
> Sure it is already done, have a look at: pkg/networkservice/common/authorize/client.go:62

Got it!

**Comment by denis-tingaikin** [comment]
> So that we check the authorization as early as possible in the return part of the chain.

It makes sense, will fix

**Comment by denis-tingaikin** [comment]
@edwarnicke Done!

**Pull request merged**
