### PR TITLE
Add requestcontext chain element to fill missing fields for requests

### PR DESCRIPTION
**Pull request by haiodo**
Add requestcontext chain element to fill missing fields for requests

Signed-off-by: Andrey Sobolev <haiodo@gmail.com>

### CODE REVIEW

**Review by denis-tingajkin — APPROVED** [review]

**Comment by denis-tingajkin** [comment]
@edwarnicke Could you please take a look at this PR?

**Comment by edwarnicke** [comment]
@haiodo Could you say a bit more about the purpose here?  It looks like this is just rolling up a small amount of boiler plate to fill in empty Connection and ConnectionContext if they are not present?

**Comment by haiodo** [comment]
> @haiodo Could you say a bit more about the purpose here? It looks like this is just rolling up a small amount of boiler plate to fill in empty Connection and ConnectionContext if they are not present?

Hi @edwarnicke, yes just for this purpose right.

**Comment by denis-tingajkin** [comment]
@edwarnicke Can we go with this PR?

**Comment by denis-tingaikin** [comment]
This is outdated.

Probably we can consider this in https://github.com/networkservicemesh/sdk/issues/729

**Pull request closed without merging**
