### PR TITLE
move sriov tokens from sdk-sriov into sdk repo

### PR DESCRIPTION
**Pull request by pperiyasamy**
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>

## Description
Move tokens package from sdk-sriov repo into sdk repo as per feedback [here](https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163#issuecomment-839757019)

## Issue link

https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163

## How Has This Been Tested?

- [x] Added unit testing to cover
- [ ] Tested manually
- [ ] Tested by integration testing
- [ ] Have not tested

## Types of changes

- [ ] Bug fix
- [ ] New functionallity
- [ ] Documentation
- [x] Refactoring
- [ ] CI

### CODE REVIEW

**Comment by edwarnicke** [comment]
@pperiyasamy I am a little confused why SRIOV tokens are moving from sdk-sriov to sdk.  I'm not saying its not a good idea... I'm saying I'm confused :)

Could you help me understand the context a bit better?

**Comment by pperiyasamy** [comment]
> Could you help me understand the context a bit better?

@edwarnicke we're moving sriov token device plugin server from cmd-forwarder-sriov into sdk-k8s repo to fix this [issue](https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163), the dp server depends on "github.com/networkservicemesh/sdk-sriov/pkg/tools/tokens" package, but this pkg is self contained one, so moving it into sdk so that this [change](https://github.com/networkservicemesh/sdk-k8s/pull/155) can just rely on sdk repo (just refer to this [comment](https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163#issuecomment-839757019))

**Review by denis-tingaikin — COMMENTED** [review]
Why do we need to move SRIOV things into sdk?

**Comment by denis-tingaikin** [comment]
@pperiyasamy Can we follow this suggestion? https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163#issuecomment-839715230 
In this case we do not need to modify sdk :)

**Comment by pperiyasamy** [comment]
> @pperiyasamy Can we follow this suggestion? [networkservicemesh/cmd-forwarder-sriov#163 (comment)](https://github.com/networkservicemesh/cmd-forwarder-sriov/issues/163#issuecomment-839715230)
> In this case, we do not need to modify sdk :)

@denis-tingaikin yes, that makes sense, just updated this [PR](https://github.com/networkservicemesh/sdk-k8s/pull/155) based on your suggestion. can you review it (I couldn't add you folks for review in that PR) ?

**Pull request closed without merging**
